language: java

jdk:
  - openjdk11

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    bucket: awscodepipeline-pokemon-buket
    region: us-west-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: awscodepipeline-pokemon-buket
    key: latest/pokemon-battle.zip
    bundle_type: zip
    application: MyPokemonApp
    deployment_group: MyDeploymentGroup
    region: us-west-1
    on:
      all_branches: true

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - ls -la
  - mv latest.zip dpl_cd_upload/latest.zip

