# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-battle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-battle
  template:
    metadata:
      labels:
        app: pokemon-battle
    spec:
      containers:
        - name: app
          image: suarez/pokemon-battle-java:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: pokemon-battle
spec:
  selector:
    app: pokemon-battle
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
